// CloudFront Function (viewer-request) that maps clean URLs to the static
// HTML files generated by Next.js `output: 'export'`.
//
//   /                → / (handled by DefaultRootObject = index.html)
//   /admin           → /admin.html
//   /assets/x.css    → /assets/x.css (untouched — has an extension)
//   /admin/          → /admin/index.html (folder-style URL)
function handler(event) {
  var request = event.request;
  var uri = request.uri;

  if (uri.endsWith('/')) {
    request.uri += 'index.html';
  } else if (!uri.includes('.')) {
    request.uri += '.html';
  }

  return request;
}
